### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by 00KL** [chrux/gitlab-bitbutcket-cicd#2]
I'm getting this error message:
Traceback (most recent call last):
  File "export.py", line 142, in <module>
    main()
  File "/home/lucas/repositorios/env_bucket/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucas/repositorios/env_bucket/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lucas/repositorios/env_bucket/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucas/repositorios/env_bucket/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "export.py", line 116, in main
    bitbucket_pipeline_data['pipelines']['default'].append({ step: step })
TypeError: unhashable type: 'dict'

Can someone help?

**Comment by TheAvalanche** [comment]
Replace line 116:
bitbucket_pipeline_data['pipelines']['default'].append({ step: step })

With
bitbucket_pipeline_data['pipelines']['default'].append({ 'step': step })
